const types = {
  SET_LOCALE: 'SET_LOCALE',
  SET_CURRENT_TYPE: 'SET_CURRENT_TYPE',
  SET_CLIENT_GEO: 'SET_CLIENT_GEO',
  SET_LAST_CLICKED_DAY: 'SET_LAST_CLICKED_DAY',
  SET_LAST_CLICKED_LUNAR_NUMBER: 'SET_LAST_CLICKED_LUNAR_NUMBER',
  SET_NOT_FIRST_TIME: 'SET_NOT_FIRST_TIME',
  SET_TODAY: 'SET_TODAY',
  SET_MODAL: 'SET_MODAL',
  SET_USER: 'SET_USER'
}

export default types
